const mongoose=require('mongoose')
const productSchema=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    discription:{
        type:String,
        required:true
    },
    catogary:{
        type:String,
        required:true
    },
    image:{
        type:Array
    },
    quantity:{
        type:Number,
        required:0
    },
    status:{
        type:Boolean,
        default:true
    },
    blocked:{
        type:String,
        default:0
    },
    discount:{
        type:Number,
        required:true
    }
})
module.exports=mongoose.model('product',productSchema)